language: python
sudo: false
cache: pip

python:
  - "3.5"
  - "3.4"
  - "2.7"

branches:
  only:
    - master

# command to install requirements
install:
  - python setup.py -q develop
  - pip install -r requirements-test.txt

before_script:
  - ./runflake8
  - ./runisort

# command to run tests, e.g. python setup.py test
script:
  - nosetests --with-coverage --cover-package=netjsonconfig

after_success:
  coveralls
