language: python
sudo: false
cache: pip

python:
  - "3.6"
  - "3.7"

branches:
  only:
    - master

before_install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements-test.txt
  # temporary: remove when openwisp-utils 0.5.0 is released
  - pip install -U https://github.com/openwisp/openwisp-utils/tarball/master#egg=openwisp_utils[qa]

install:
  - python setup.py -q develop

before_script:
  - ./run-qa-checks

script:
  - nose2 --with-coverage --coverage=netjsonconfig

after_success:
  coveralls
